#!/bin/bash
#
# Gitea Auto-Setup Script
# Automatically creates admin user and generates API token on first install
# 
# Security considerations:
# - Token is generated using cryptographically secure random bytes
# - Token is stored in a protected file with restricted permissions
# - Admin password is also auto-generated and stored securely
#

set -e

# Configuration
GITEA_CONTAINER="${GITEA_CONTAINER:-musical-gitea-local}"
GITEA_URL="${GITEA_URL:-http://localhost:17101}"
GITEA_ADMIN_USER="${GITEA_ADMIN_USER:-musical}"
GITEA_ADMIN_EMAIL="${GITEA_ADMIN_EMAIL:-admin@musical.local}"
SECRETS_DIR="${SECRETS_DIR:-/root/.musical/secrets}"
TOKEN_FILE="${SECRETS_DIR}/gitea-token"
CREDENTIALS_FILE="${SECRETS_DIR}/gitea-credentials"
SETUP_MARKER="${SECRETS_DIR}/.gitea-setup-complete"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

log_info() {
    echo -e "${GREEN}[INFO]${NC} $1"
}

log_warn() {
    echo -e "${YELLOW}[WARN]${NC} $1"
}

log_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

# Generate cryptographically secure random string
generate_secure_token() {
    local length=${1:-32}
    # Use /dev/urandom for cryptographic randomness
    head -c 256 /dev/urandom | LC_ALL=C tr -dc 'a-zA-Z0-9' | head -c "$length"
}

# Check if Gitea is ready
wait_for_gitea() {
    local max_attempts=30
    local attempt=0
    
    log_info "Waiting for Gitea to be ready..."
    
    while [ $attempt -lt $max_attempts ]; do
        if curl -s -o /dev/null -w "%{http_code}" "$GITEA_URL/api/v1/version" 2>/dev/null | grep -q "200"; then
            log_info "Gitea is ready!"
            return 0
        fi
        
        attempt=$((attempt + 1))
        echo -n "."
        sleep 2
    done
    
    log_error "Gitea did not become ready in time"
    return 1
}

# Create secrets directory with proper permissions
setup_secrets_dir() {
    if [ ! -d "$SECRETS_DIR" ]; then
        log_info "Creating secrets directory: $SECRETS_DIR"
        mkdir -p "$SECRETS_DIR"
    fi
    
    # Secure the directory - only root can read/write
    chmod 700 "$SECRETS_DIR"
}

# Check if setup was already completed
is_setup_complete() {
    if [ -f "$SETUP_MARKER" ] && [ -f "$TOKEN_FILE" ]; then
        log_info "Gitea setup already completed"
        return 0
    fi
    return 1
}

# Create admin user in Gitea
create_admin_user() {
    local password="$1"
    
    log_info "Creating Gitea admin user: $GITEA_ADMIN_USER"
    
    # Try to create user via Gitea CLI inside container
    docker exec -u git "$GITEA_CONTAINER" gitea admin user create \
        --username "$GITEA_ADMIN_USER" \
        --password "$password" \
        --email "$GITEA_ADMIN_EMAIL" \
        --admin \
        --must-change-password=false 2>/dev/null || {
            # User might already exist, try to reset password
            log_warn "User might already exist, attempting password reset..."
            docker exec -u git "$GITEA_CONTAINER" gitea admin user change-password \
                --username "$GITEA_ADMIN_USER" \
                --password "$password" 2>/dev/null || true
        }
    
    log_info "Admin user created/updated: $GITEA_ADMIN_USER"
}

# Generate API token via Gitea API
generate_api_token() {
    local password="$1"
    local token_name="musical-local-server-$(date +%s)"
    
    log_info "Generating API token for user: $GITEA_ADMIN_USER"
    
    # Create token via API using basic auth
    local response=$(curl -s -X POST \
        -u "$GITEA_ADMIN_USER:$password" \
        -H "Content-Type: application/json" \
        -d "{\"name\": \"$token_name\", \"scopes\": [\"write:repository\", \"write:user\", \"write:organization\"]}" \
        "$GITEA_URL/api/v1/users/$GITEA_ADMIN_USER/tokens")
    
    # Extract token from response
    local token=$(echo "$response" | grep -o '"sha1":"[^"]*"' | cut -d'"' -f4)
    
    if [ -z "$token" ]; then
        log_error "Failed to generate API token. Response: $response"
        return 1
    fi
    
    echo "$token"
}

# Save credentials securely
save_credentials() {
    local password="$1"
    local token="$2"
    
    # Save token to file with restricted permissions
    echo "$token" > "$TOKEN_FILE"
    chmod 600 "$TOKEN_FILE"
    
    # Save credentials (for reference/recovery)
    cat > "$CREDENTIALS_FILE" << EOF
# Gitea Credentials - Auto-generated by Musical.run
# Generated: $(date -Iseconds)
# 
# WARNING: Keep this file secure!
#

GITEA_URL=$GITEA_URL
GITEA_USERNAME=$GITEA_ADMIN_USER
GITEA_TOKEN=$token
GITEA_ADMIN_PASSWORD=$password
EOF
    chmod 600 "$CREDENTIALS_FILE"
    
    log_info "Credentials saved to: $CREDENTIALS_FILE"
    log_info "Token saved to: $TOKEN_FILE"
}

# Create organization for projects
create_organization() {
    local token="$1"
    local org_name="${GITEA_ORGANIZATION:-musical}"
    
    log_info "Creating organization: $org_name"
    
    curl -s -X POST \
        -H "Authorization: token $token" \
        -H "Content-Type: application/json" \
        -d "{\"username\": \"$org_name\", \"full_name\": \"Musical.run Projects\", \"visibility\": \"private\"}" \
        "$GITEA_URL/api/v1/orgs" > /dev/null 2>&1 || {
            log_warn "Organization might already exist"
        }
}

# Update .env file with generated token
update_env_file() {
    local token="$1"
    local password="$2"
    local env_file="${ENV_FILE:-/root/local-server/.env}"
    
    log_info "Updating environment file: $env_file"
    
    # Create .env if it doesn't exist
    touch "$env_file"
    
    # Remove existing Gitea settings
    sed -i '/^GITEA_TOKEN=/d' "$env_file" 2>/dev/null || true
    sed -i '/^GITEA_USERNAME=/d' "$env_file" 2>/dev/null || true
    sed -i '/^GITEA_ORGANIZATION=/d' "$env_file" 2>/dev/null || true
    
    # Append new settings
    cat >> "$env_file" << EOF

# Gitea Configuration (auto-generated)
GITEA_TOKEN=$token
GITEA_USERNAME=$GITEA_ADMIN_USER
GITEA_ORGANIZATION=musical
EOF
    
    chmod 600 "$env_file"
    log_info "Environment file updated"
}

# Mark setup as complete
mark_setup_complete() {
    echo "Setup completed at: $(date -Iseconds)" > "$SETUP_MARKER"
    chmod 600 "$SETUP_MARKER"
}

# Main setup flow
main() {
    log_info "=== Gitea Auto-Setup Script ==="
    log_info "Container: $GITEA_CONTAINER"
    log_info "URL: $GITEA_URL"
    
    # Check if already setup
    if is_setup_complete; then
        local existing_token=$(cat "$TOKEN_FILE" 2>/dev/null)
        if [ -n "$existing_token" ]; then
            log_info "Using existing token from: $TOKEN_FILE"
            echo "$existing_token"
            return 0
        fi
    fi
    
    # Setup secrets directory
    setup_secrets_dir
    
    # Wait for Gitea to be ready
    wait_for_gitea || exit 1
    
    # Generate secure password for admin user
    local admin_password=$(generate_secure_token 24)
    log_info "Generated secure admin password"
    
    # Create admin user
    create_admin_user "$admin_password"
    
    # Give Gitea a moment to process
    sleep 2
    
    # Generate API token
    local api_token=$(generate_api_token "$admin_password")
    if [ -z "$api_token" ]; then
        log_error "Failed to generate API token"
        exit 1
    fi
    log_info "API token generated successfully"
    
    # Save credentials
    save_credentials "$admin_password" "$api_token"
    
    # Create organization
    create_organization "$api_token"
    
    # Update .env file
    update_env_file "$api_token" "$admin_password"
    
    # Mark setup as complete
    mark_setup_complete
    
    log_info "=== Gitea Auto-Setup Complete ==="
    log_info ""
    log_info "Gitea is ready to use!"
    log_info "  URL: $GITEA_URL"
    log_info "  Username: $GITEA_ADMIN_USER"
    log_info "  Token file: $TOKEN_FILE"
    log_info ""
    log_info "Restart the local-server to apply the new configuration:"
    log_info "  docker-compose restart musical-local-server"
    
    # Output the token for use
    echo "$api_token"
}

# Run main
main "$@"
